# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lizb0907.github.io
date_format: "ordinal"
title: java服务端~我的学习之路
subtitle: "坚持做好一件事"
description: "李志标的个人博客"
keywords: java, 服务器, 学习, 记录
timezone: BeiJing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: lzb
github_username: lizb0907
location: BeiJing, China
email: lzbswf@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lizb0907/lizb0907.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#    owner: lizb0907
#    repo: lizb0907.github.io
#    oauth:
#        client_id: 5d12dbc76b919abb9980
#       client_secret: fb99fec6ef50ddddd166926a71d1310266c7b202
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: lizb0907
    repo: lizb0907.github.io
    clientID: 2c8e4f88a570ab8445bc
    clientSecret: b88e3522c090461f3f51675931bc810cf090d65d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-139242672-1
